name: store_ify
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  conditional_builder_null_safety: ^0.0.6
  dartz: ^0.10.1
  dio: ^5.3.4
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  geocoding: ^2.1.1
  get_it: ^7.6.4
  internet_connection_checker: ^1.0.0+1
  location: ^5.0.3
  pinput: ^3.0.1
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 900

    - family: Potta One
      fonts:
        - asset: assets/fonts/PottaOne-Regular.ttf
          weight: 400

flutter_assets:
  assets_path: assets/
  output_path: lib/core/utils/
  filename: app_assets.dart
  field_prefix: null

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
