name: store_ify
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Purify dart code
  dartz: ^0.10.1
  # HTTP networking package
  dio: ^5.3.4
  # Implement value based equality
  equatable: ^2.0.5
  # State management
  flutter_bloc: ^8.1.3
  # Updating app's launcher icon
  flutter_launcher_icons: ^0.13.1
  # For animated loading indicators
  flutter_spinkit: ^5.2.0
  # Easily create toast messages
  fluttertoast: ^8.2.4
  # Provides easy geocoding and reverse-geocoding features
  geocoding: ^2.1.1
  # Simple direct Service Locator that allows to access the concrete implementation from everywhere
  get_it: ^7.6.4
  # Dart library that checks for internet
  internet_connection_checker: ^1.0.0+1
  # Provides easy access to device's location in real-time
  location: ^5.0.3
  # (OTP) text field
  pinput: ^3.0.1
  # Flutter plugin for reading and writing simple key-value pairs for cache
  shared_preferences: ^2.2.2
  # Customizable animated page indicator
  smooth_page_indicator: ^1.1.0
  # A flutter plugin for adapting screen and font size.Guaranteed to look good on different models
  flutter_screenutil: ^5.9.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints to encourage good coding practices
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 900

    - family: Potta One
      fonts:
        - asset: assets/fonts/PottaOne-Regular.ttf
          weight: 400

flutter_assets:
  assets_path: assets/
  output_path: lib/core/utils/
  filename: app_assets.dart
  field_prefix: null

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
