// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPhnLPWq1rAlwy75YyaB8XX4u6HWQciZk',
    appId: '1:74739450491:web:6939f0f7ca162c288e58de',
    messagingSenderId: '74739450491',
    projectId: 'store-ify-ecommerce',
    authDomain: 'store-ify-ecommerce.firebaseapp.com',
    storageBucket: 'store-ify-ecommerce.appspot.com',
    measurementId: 'G-EQD8V7EV3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1RcgQdie4CIh6UMl1fH1Ze5VFk8uP6jI',
    appId: '1:74739450491:android:0a91c6343db878cb8e58de',
    messagingSenderId: '74739450491',
    projectId: 'store-ify-ecommerce',
    storageBucket: 'store-ify-ecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRb8UgDVHf6MMQUx9PCzjOyYV88u88fIU',
    appId: '1:74739450491:ios:bd1f70b20eb2a84e8e58de',
    messagingSenderId: '74739450491',
    projectId: 'store-ify-ecommerce',
    storageBucket: 'store-ify-ecommerce.appspot.com',
    iosBundleId: 'com.example.storeIfy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRb8UgDVHf6MMQUx9PCzjOyYV88u88fIU',
    appId: '1:74739450491:ios:5d3b9f58fe8c423f8e58de',
    messagingSenderId: '74739450491',
    projectId: 'store-ify-ecommerce',
    storageBucket: 'store-ify-ecommerce.appspot.com',
    iosBundleId: 'com.example.storeIfy.RunnerTests',
  );
}
